services:
  db:
    image: mysql:8
    container_name: mysql-db
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./doc/data.sql:/docker-entrypoint-initdb.d/data.sql

volumes:
  mysql_data: